### ISSUE TITLE
XeGTAO is extremely heavy on 4K resolution.

### ISSUE THREAD

**Issue by wroyca** [GarrettGunnell/AcerolaFX#19]
As the title suggests, XeGTAO is extremely heavy on 4K resolution and barely reaches 60 fps on an Nvidia GeForce RTX 3070 Ti. Unfortunately, lower resolution led to some terrible grain with 4K display. There's probably not a lot that can be done but perhaps there's some optimization trick to ease the burden of the GPU? 😅

**Comment by GarrettGunnell** [comment]
Nope! Welcome to 4k rendering

**Comment by GarrettGunnell** [comment]
Jokes aside it's already as optimized as it can get within the bounds of GShade, if this were an actual game I was making then I would use an upscaling algorithm but that's not a possible solution here. 

XeGTAO is made to be used with temporal anti aliasing since it allows you to get denoising for basically free, but since TAA isn't possible in GShade I have to use the bilateral filter to denoise which is a considerably costly effect and is made even worse at 4k since you have to do a huge kernel size to get the same results at 4k as you would at a lower resolution.

With the graphics rehaul coming in the next expansion, the higher poly character models should allow for less reliance on the bilateral filter to reduce artifacts which will make the effect much faster.

**Comment by wroyca** [comment]
> Jokes aside it's already as optimized as it can get within the bounds of GShade, if this were an actual game I was making then I would use an upscaling algorithm but that's not a possible solution here.
> 
> XeGTAO is made to be used with temporal anti aliasing since it allows you to get denoising for basically free, but since TAA isn't possible in GShade I have to use the bilateral filter to denoise which is a considerably costly effect and is made even worse at 4k since you have to do a huge kernel size to get the same results at 4k as you would at a lower resolution.
> 
> With the graphics rehaul coming in the next expansion, the higher poly character models should allow for less reliance on the bilateral filter to reduce artifacts which will make the effect much faster.

That makes sense. Let's pray that the superior poly character models are good enough! 🙏
