### ISSUE TITLE
The shader still does not work for me on the most recent version of GShade

### ISSUE THREAD

**Issue by ExtraThicc1993** [GarrettGunnell/AcerolaFX#29]
Title.

Basically the issue (that Acerola also seems to be aware of) persists since the last update. When I talked to him he said it is Gshades fault and there won't be a fix on his end. When I talked to the Gshade people on discord, they say it is an issue of the shaders compatibility and to not expect a fix on their end.

Iirc on the Gshade Discord they mentioned sth. along the lines of a cloning function that ppl. used to make their shaders with no longer working, rendering all shaders that used this function useless.

Multiple re-installs didn't do anything for me (neither acerola nor gshade).

Is there any solution for this and who is at fault in the end?

**Comment by GarrettGunnell** [comment]
There seems to be a bit of a miscommunication between you and the GShade people. My gameplay presets are unaffected by the lack of shader cloning in GShade 5, it was a new update to GShade that appeared to break presets for a lot of people (not me though). This is what I mean when I say it's a GShade problem not a problem with my shaders/presets.

Many people who had the issue said it was fixed by doing a fresh reinstall of gshade and redownload of my shaders. Alternatively you can try putting the shaders into a new folder and then adding that folder to the search paths in the GShade settings and then clicking `Reload`.
