### ISSUE TITLE
HUD bug with while using AcerolaFX

### ISSUE THREAD

**Issue by Febuol** [GarrettGunnell/AcerolaFX#34]
This is only with Bard, Monk and Astro. Is it fixable ?
![ffxiv_dx11 2023-03-06 01-05-46](https://user-images.githubusercontent.com/127072987/223018242-9bf8db76-46ec-4312-bbf6-7370098798e5.png)
![ffxiv_dx11 2023-03-06 01-10-22](https://user-images.githubusercontent.com/127072987/223018252-f1cb5961-b007-4aad-8238-e8c616a06d7e.png)
![ffxiv_dx11 2023-03-06 01-15-24](https://user-images.githubusercontent.com/127072987/223018254-1e93b711-9e76-4237-b0fb-c5988322e206.png)

**Comment by GarrettGunnell** [comment]
Unfortunately no this is not fixable with ReShade as it's an issue with the ui mask that ReShade produces. GShade did not have this problem, but since the community decided to destroy it we have to live with the consequences.

One solution is to go into your HUD layout settings, click on the arcana gauge, and click the gear icon as demonstrated below:

![ffxiv_dx11_z8zMkj80VE](https://user-images.githubusercontent.com/32238555/223019830-050b9349-5c50-4e5d-af1f-e266ad5f5e5d.png)

and then click `Switch Job Gauge to Simple Mode` which will change it to a less visually interesting UI piece but without the obvious UI mask square.
![ffxiv_dx11_olusXVzntm](https://user-images.githubusercontent.com/32238555/223020067-1380fd42-3f75-413e-b8a8-0c26ca78d0ba.png)

![ffxiv_dx11_PuFZPWYWEe](https://user-images.githubusercontent.com/32238555/223020119-f4cf9e65-dbb0-4d3f-aa5d-b622c2fd205c.png)
