### ISSUE TITLE
Blurry box around some Job Gauges

### ISSUE THREAD

**Issue by Elanapoeia** [GarrettGunnell/AcerolaFX#38]
I got a blurry box around several job gauges when using these shaders, but not on other shaders (like the Gshade imports). I didn't modify them, and they're present on low, middle and high gameplay settings.

Jobs that are affected:
Bard (https://i.imgur.com/ZOu97Bv.png)
Astro (https://i.imgur.com/1Pnl08W.png)
Monk (https://i.imgur.com/PRJ9YK3.png)

Other jobs are totally fine.

**Comment by GarrettGunnell** [comment]
This is an issue with ReShade's ui mask that it provides to the shaders, it is not an issue with the shaders.

GShade fixes this issue somehow, so if you use GShade instead of ReShade then the problem will not be there.

You can "fix" it by changing the job guage to its minimalist variant, which you can see how to do [here](https://github.com/GarrettGunnell/AcerolaFX/issues/34)
