### ISSUE TITLE
XeGTAO shading is low poly, sharp edges

### ISSUE THREAD

**Issue by yaomtc** [GarrettGunnell/AcerolaFX#41]
Off
![XeGTAO off](https://github.com/GarrettGunnell/AcerolaFX/assets/5534045/cca3027e-40da-492e-b40a-a531329c8af0)
On:
![XeGTAO on](https://github.com/GarrettGunnell/AcerolaFX/assets/5534045/23430ba0-ff85-4bb3-807e-4a4dfdff938f)

If I use another shader with qUINT_mxao, there's blockiness there too, but I can use its "smooth normals" settings to reduce it: 

https://www.patreon.com/posts/using-mxao-guide-54519401

> I’ve enabled IL (indirect lighting), as well as two-layer. Two-layer gives you some extra settings under the ‘Double Layer’ section. It can be useful for a little bit extra fine tuning, but isn’t strictly necessary. You will want to turn on Smooth Normals though, to help reduce a little bit of the blockiness you get with a low-poly game

I can't find any tweaks that will reduce the blockiness of XeGTAO though.

I've tried replacing the preset files to revert everything to their original values, and tried adjusting XeGTAO settings but nothing seems to help.

If you can't reproduce it, it might be because I'm playing on Linux, so [DXVK](https://github.com/doitsujin/dxvk) might be a factor.

**Comment by GarrettGunnell** [comment]
it's not the xegtao that is low poly, it's ff14 that is low poly, since the effect doesnt have access to the real normals of the scene it has to reconstruct the normals from the low poly geometry resulting in the blocky look on some meshes, usually naked people because those models are really old. The blur settings exist to try and mitigate it but if you play on a high resolution (>1080p) it's gonna be even worse lol.

This is something that can be fixed with addons but I dont want to use them as they are questionably bannable, but other people have their own AO shaders that do make use of addons to fix it if this is too much of an issue for you. 

But when the graphics overhaul comes out with higher poly character models this issue will be pretty much resolved.

**Comment by yaomtc** [comment]
Thank you, glad to know it's not just me. 

I just realized I can put MXAO below AcerolaFXEnd, and it works. I'll use that for now!
