### ISSUE TITLE
XEGTAO issue with 99 3D Resolution scaling

### ISSUE THREAD

**Issue by Beamox** [GarrettGunnell/AcerolaFX#50]
Since the update when i put the 3D resolution scaling to 99, it seems like the XEGTA plugin is off scale on my character (on left side). Can't seem to fix it with the sliders, any ideas?
![xegtao issue](https://github.com/user-attachments/assets/65ccb076-247b-44cb-8b6c-2637d526bc72)

**Comment by GarrettGunnell** [comment]
Yes cause you have changed the resolution at which the game is natively rendered. The 99 trick just results in a more sharpened final render because that's what FSR/DLSS does to fake new detail, if you want the same result you can just increase the sharpness in the sharpness shader.

Otherwise follow these steps from ipsusu: https://x.com/ipsusu/status/1806629546361225521

**Comment by Beamox** [comment]
Hello! The ipsu fix worked perfectly thanks a bunch!

I did try the sharpness shader but with the tick to 100 when you zoom out the hair textures tend to blur a lot, so i prefered to put it a 99.
